import { Shop, SaleEvent, Model, PriceSnapshot, DealAlert } from "@/types/database";

export const SHOPS: Shop[] = [
  {
    slug: "zalando",
    name: "Zalando",
    logo: "/shops/zalando.svg",
    url: "https://www.zalando.de",
    color: "#FF6900",
    activeDeals: 24,
  },
  {
    slug: "aboutyou",
    name: "About You",
    logo: "/shops/aboutyou.svg",
    url: "https://www.aboutyou.de",
    color: "#000000",
    activeDeals: 18,
  },
  {
    slug: "snipes",
    name: "Snipes",
    logo: "/shops/snipes.svg",
    url: "https://www.snipes.com",
    color: "#FFD700",
    activeDeals: 12,
  },
  {
    slug: "snkrs",
    name: "SNKRS",
    logo: "/shops/snkrs.svg",
    url: "https://www.snkrs.com",
    color: "#111111",
    activeDeals: 8,
  },
];

export const MOCK_EVENTS: SaleEvent[] = [
  {
    id: "1",
    title: "Zalando Summer Sale",
    date: "2026-06-15",
    description: "Up to 50% off on selected sneakers",
    site: "zalando",
  },
  {
    id: "2",
    title: "Nike Air Max Day",
    date: "2026-03-26",
    description: "Exclusive drops and discounts on Air Max models",
    site: "snkrs",
  },
  {
    id: "3",
    title: "Snipes Black Friday",
    date: "2026-11-27",
    description: "Biggest sale event of the year",
    site: "snipes",
  },
  {
    id: "4",
    title: "About You Spring Deals",
    date: "2026-04-10",
    description: "New season arrivals with launch discounts",
    site: "aboutyou",
  },
];

export const MOCK_MODELS: Model[] = [
  {
    id: "1",
    name: "Air Max 90",
    brand: "Nike",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=Air+Max+90",
    category: "Lifestyle",
    created_by: "system",
    created_at: "2026-01-01",
  },
  {
    id: "2",
    name: "Ultraboost 22",
    brand: "Adidas",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=Ultraboost+22",
    category: "Running",
    created_by: "system",
    created_at: "2026-01-01",
  },
  {
    id: "3",
    name: "550",
    brand: "New Balance",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=NB+550",
    category: "Lifestyle",
    created_by: "system",
    created_at: "2026-01-01",
  },
  {
    id: "4",
    name: "Dunk Low Retro",
    brand: "Nike",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=Dunk+Low",
    category: "Lifestyle",
    created_by: "system",
    created_at: "2026-01-01",
  },
  {
    id: "5",
    name: "Forum Low",
    brand: "Adidas",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=Forum+Low",
    category: "Lifestyle",
    created_by: "system",
    created_at: "2026-01-01",
  },
  {
    id: "6",
    name: "Gel-1130",
    brand: "Asics",
    image_url: "https://placehold.co/400x400/1A1A1A/FFFFFF?text=Gel-1130",
    category: "Running",
    created_by: "system",
    created_at: "2026-01-01",
  },
];

export const MOCK_SNAPSHOTS: (PriceSnapshot & { model?: Model })[] = [
  {
    id: "1",
    model_id: "1",
    site: "zalando",
    price: 89.99,
    original_price: 149.99,
    discount_pct: 40,
    url: "https://zalando.de/nike-air-max-90",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[0],
  },
  {
    id: "2",
    model_id: "2",
    site: "aboutyou",
    price: 109.99,
    original_price: 179.99,
    discount_pct: 39,
    url: "https://aboutyou.de/adidas-ultraboost",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[1],
  },
  {
    id: "3",
    model_id: "3",
    site: "snipes",
    price: 79.99,
    original_price: 129.99,
    discount_pct: 38,
    url: "https://snipes.com/new-balance-550",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[2],
  },
  {
    id: "4",
    model_id: "4",
    site: "zalando",
    price: 74.99,
    original_price: 119.99,
    discount_pct: 37,
    url: "https://zalando.de/nike-dunk-low",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[3],
  },
  {
    id: "5",
    model_id: "5",
    site: "snkrs",
    price: 59.99,
    original_price: 109.99,
    discount_pct: 45,
    url: "https://snkrs.com/adidas-forum-low",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[4],
  },
  {
    id: "6",
    model_id: "6",
    site: "aboutyou",
    price: 94.99,
    original_price: 139.99,
    discount_pct: 32,
    url: "https://aboutyou.de/asics-gel-1130",
    checked_at: "2026-03-29T10:00:00Z",
    model: MOCK_MODELS[5],
  },
];

export const MOCK_ALERTS: DealAlert[] = [
  {
    id: "1",
    user_id: "user1",
    model_id: "1",
    site: "zalando",
    old_price: 149.99,
    new_price: 89.99,
    discount_pct: 40,
    url: "https://zalando.de/nike-air-max-90",
    created_at: "2026-03-29T09:30:00Z",
    model: MOCK_MODELS[0],
  },
  {
    id: "2",
    user_id: "user1",
    model_id: "5",
    site: "snkrs",
    old_price: 109.99,
    new_price: 59.99,
    discount_pct: 45,
    url: "https://snkrs.com/adidas-forum-low",
    created_at: "2026-03-29T08:15:00Z",
    model: MOCK_MODELS[4],
  },
  {
    id: "3",
    user_id: "user1",
    model_id: "3",
    site: "snipes",
    old_price: 129.99,
    new_price: 79.99,
    discount_pct: 38,
    url: "https://snipes.com/new-balance-550",
    created_at: "2026-03-28T14:00:00Z",
    model: MOCK_MODELS[2],
  },
  {
    id: "4",
    user_id: "user1",
    model_id: "2",
    site: "aboutyou",
    old_price: 179.99,
    new_price: 109.99,
    discount_pct: 39,
    url: "https://aboutyou.de/adidas-ultraboost",
    created_at: "2026-03-27T11:45:00Z",
    model: MOCK_MODELS[1],
  },
];

export const MOCK_PRICE_HISTORY: { date: string; price: number }[] = [
  { date: "Mar 1", price: 149.99 },
  { date: "Mar 5", price: 149.99 },
  { date: "Mar 8", price: 139.99 },
  { date: "Mar 12", price: 129.99 },
  { date: "Mar 15", price: 129.99 },
  { date: "Mar 18", price: 119.99 },
  { date: "Mar 22", price: 109.99 },
  { date: "Mar 25", price: 99.99 },
  { date: "Mar 29", price: 89.99 },
];

export const SIZE_OPTIONS = [
  36, 36.5, 37, 37.5, 38, 38.5, 39, 40, 40.5, 41, 42, 42.5, 43, 44, 44.5, 45, 46,
];

export const BRAND_OPTIONS: string[] = [
  "Nike",
  "Adidas",
  "New Balance",
  "Puma",
  "Reebok",
  "Asics",
  "Converse",
  "Vans",
  "Jordan",
  "Yeezy",
];

export const CATEGORY_OPTIONS = ["Lifestyle", "Running", "Basketball", "Skateboarding", "Training"];
